### ISSUE TITLE
It's funny, but you kind of "stole" the namespace I use for my libraries

### ISSUE THREAD

**Issue by eyalz800** [lowlander/zpp#1]
https://GitHub.com/eyalz800/

It's not like it has to be unique, we can both use this, but I wanted to let you know if you care about your namespace uniqueness

**Comment by lowlander** [comment]
It doesn't look like the two libraries (and with that the namespaces) are targeting the same developers, so I doubt there will be any problems. And the term "stole" even when it is in quotes, kind of suggest intent but since I had no idea that there was another zpp:: that is most certainly not the case.
